spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://202.81.237.45/bluewhale?useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: bluewhale
    password: 56GrciF87xKH3cZM
    driver-class-name: com.mysql.cj.jdbc.Driver



#show sql
logging:
  level:
    com:
      hp:
        dao:
          DEBUG