spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://db1.arknights.ltd:10098/bluewhale
    username: bluewhale
    password: 56GrciF87xKH3cZM
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      pool-prepared-statements: true
  mail:
    default-encoding: UTF-8
    host: smtp.exmail.qq.com
    username: admin@melco.cc
    password: 9839BurstX
    properties:
      mail:
        smtp:
          atuh: true
          starttls:
            enable: true
            required: true



mybatis-plus:
  configuration:
    cache-enabled: true



#show sql
logging:
  level:
    com:
      hp:
        dao:
          DEBUG




