spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    url: jdbc:mariadb://202.81.237.45/bluewhale
    username: bluewhale
    password: 56GrciF87xKH3cZM
    driver-class-name: org.mariadb.jdbc.Driver


#show sql
logging:
  level:
    com:
      hp:
        dao:
          DEBUG




