spring:
  mvc:
    view:
      prefix: /
      suffix: .html
---
spring:
  datasource:
    url: jdbc:mysql://202.81.231.187/bluewhale?useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: bluewhale
    password: 56GrciF87xKH3cZM
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  #配置驼峰命名法
  configLocation: #此处不能用局部configuration变量来配置
    map-underscore-to-camel-case: true


#show sql
logging:
  level:
    com:
      hp:
        dao:
          DEBUG